"""
The cmdpedia for this module was generated by running the package as a script and passing it as an argument along with the library used.

cmdpedia generator can be used by either importing the core module and calling the `generate_cmdpedia` function, or by running the package as a script.
"""


import click


@click.group()
def cli():
    """CLI group."""
    pass

@click.group()
def subcli():
    """CLI group."""
    pass

@click.group()
def subsubcli():
    """CLI group."""
    pass


cli.add_command(subcli, name='subcli')
subcli.add_command(subsubcli, name='subsubcli')


@cli.command()
@click.option("--verbose", is_flag=True, default=False, help="Enable verbose output.")
@click.option("--count", default=1, help="Number of greetings.")
@click.argument("name")
def greet(name, count, verbose):
    """Greet the user with a message."""
    if verbose:
        click.echo(f"Verbose mode enabled.")
    for _ in range(count):
        click.echo(f"Hello {name}!")


@subcli.command()
@click.argument("src")
@click.argument("dest")
@click.option("--force", is_flag=True, default=False, help="Force the copy operation.")
@click.option("--backup", is_flag=False, default=True, help="Backup before copying.")
def copy(src, dest, force, backup):
    """Copy files from src to dest."""
    click.echo(f"Copying from {src} to {dest}")
    if force:
        click.echo("Force option enabled.")
    if backup:
        click.echo("Backup will be created.")


@subsubcli.command()
@click.argument("src")
def gate(src):
    """Gate a file."""
    click.echo(f"{src} gated")


if __name__ == "__main__":
    cli()
